import { Inter } from "next/font/google";
import "../../styles/globals.css";
import AdminHeader from "@/app/components/admin-header";
import Link from "next/link";
import { MdDashboard } from "react-icons/md";
import { FaUser } from "react-icons/fa";
import { BiSolidCategoryAlt } from "react-icons/bi";
import { SiProducthunt } from "react-icons/si";
import { FaBorderNone } from "react-icons/fa";
import { IoIosLogOut } from "react-icons/io";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
  icons: {
    icon: ["/ecomm.png?v=4"],
  },
};

export default function AdminLayout({ children }) {
  return (
    <>
      <AdminHeader />
      <div className="flex gap-3">
        <div className="w-1/5">
          <div
            className="flex flex-col h-100 bg-cyan-900"
            style={{ height: "100vh" }}
          >
            <Link
              href="/admin"
              className="flex place-items-center gap-2 text-white font-bold border-b-2 p-5 hover:bg-red-500 hover:text-white"
            >
              <MdDashboard />
              Dashboard
            </Link>
            <Link
              href="/admin/users"
              className="flex place-items-center gap-2 text-white font-bold border-b-2 p-5 hover:bg-red-500 hover:text-white"
            >
              <FaUser />
              Manage Users
            </Link>
            <Link
              href="/admin/categories"
              className="flex place-items-center gap-2 text-white font-bold border-b-2 p-5 hover:bg-red-500 hover:text-white"
            >
              <BiSolidCategoryAlt />
              Manage Categories
            </Link>
            <Link
              href="/admin/books"
              className="flex place-items-center gap-2 text-white font-bold border-b-2 p-5 hover:bg-red-500 hover:text-white"
            >
              <SiProducthunt />
              Manage Product
            </Link>
            <Link
              href="/admin/orders"
              className="flex place-items-center gap-2 text-white font-bold border-b-2 p-5 hover:bg-red-500 hover:text-white"
            >
              <FaBorderNone />
              Manage Orders
            </Link>
            <Link
              href="#"
              className="flex place-items-center gap-2 text-white font-bold border-b-2 p-5 hover:bg-red-500 hover:text-white"
            >
              <IoIosLogOut />
              Logout
            </Link>
          </div>
        </div>
        <div className="w-3/4">{children}</div>
      </div>
    </>
  );
}
