import "./styles/globals.css";
import HomeHeader from "./components/home-header";
import { Providers } from "./provider";
import { getServerSession } from "next-auth";
import AuthProvider from "./utils/session-provider";

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
  icons: {
    icon: ["/ecomm.png?v=4"],
  },
};

export default async function RootLayout({ children }) {
  
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        {/* components aur routes have access to this session after login etc */}
        <AuthProvider session={session}>
          <HomeHeader />
          <Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
